name: .NET Desktop Build

on:
  push:
    tags:
      - '*'
    branches:
      - 'dotnet10'
  pull_request:
    branches:
      - 'dotnet10'

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        dotnet_version: [ 8, 9, 10 ]
        msbuild_target: [ x64, x86, ARM64 ]
        include:
          - msbuild_target: x64
            lowercase_target: x64
            crossbuild_target: x86_x64
          - msbuild_target: x86
            lowercase_target: x86
            crossbuild_target: x86
          - msbuild_target: ARM64
            lowercase_target: arm64
            crossbuild_target: x86_arm64

    env:
      TARGET_PLATFORM: ${{ matrix.msbuild_target }}
    runs-on: windows-2025-vs2026
    # Expected works on Windows-2025

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          show-progress: false
      # - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            ${{ matrix.dotnet_version }}.0.x
            10.0.x

      # Build libwebp
      # mkdir libwebp\\${{ matrix.msbuild_target }}build
      # Enable build when VS2026 is ready
      - name: Checkout libwebp
        shell: cmd
        run: |
          git clone -b 1.6.0 https://github.com/webmproject/libwebp.git libwebp-160
          cd libwebp-160
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.crossbuild_target }}
          nmake /f Makefile.vc CFG=release-dynamic RTLIBCFG=dynamic ARCH=${{ matrix.lowercase_target }} OBJDIR=output
          cp output/release-dynamic/${{ matrix.lowercase_target }}/bin/*.dll ../libwebp/${{ matrix.msbuild_target }}build/

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore
      # Build the solution
      - name: Build
        run: dotnet build mvlView.sln -c Release -f net${{ matrix.dotnet_version }}.0-windows /p:Platform="${{ matrix.lowercase_target }}"

      # Publish the artifacts
      - name: Publish Artifact
        if: success()
        uses: actions/upload-artifact@v6
        with:
          name: MvlView_${{ matrix.lowercase_target }}_net${{ matrix.dotnet_version }}
          path: mvlView/bin/${{ matrix.msbuild_target }}/Release/net${{ matrix.dotnet_version }}.0-windows

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download from Github
        uses: actions/download-artifact@v7
        with:
          path: assets

      - name: Re-zip artifacts
        run: |
          cd assets
          for dir in */ ; do
            zip -r "${dir%/}.zip" "$dir"
          done
        shell: bash

      - name: Release to Github
        uses: softprops/action-gh-release@v2
        with:
          files: |
            assets/*.zip
